### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by Circle-Developer** [AlessandroKuz/CaliFlow#4]
Hey there, just letting you know that there is a spelling mistake in `workout_choice.py`.
```
    if user_type == USER_TYPE[0]:
        print("TUTORIAL: \nYou can either choose all your exercises togheter", 
```
It's written *togheter*.

**Comment by AlessandroKuz** [comment]
Thanks! Already fixed it in the development branch

**Comment by AlessandroKuz** [comment]
Thanks! Already fixed it in the development branch

**Comment by Circle-Developer** [comment]
:+1:
